baseURL = "/"
title = "작가의 블로그"
languageCode = "ko-KR"
DefaultContentLanguage = "ko" # Change this to change the site's language
theme = "hugo.386k"
preserveTaxonomyNames = true

[params]

# The name to display as main title in the home page
mainpagetitle = "호롤롤로!"

# The subtitle to display under the title in the home page
mainpagesubtitle = "호롤롤로 블로그, 임시테마. 테마 쓸만한거 찾아보는 중"



# The description of your website. It will be displayed in the home 
mainpagedesc = "5SKYR24FSXWZLGHMROQOVMEAFQQOZF5M5K4LB24KSQQOZBE45WNYJ3E5TAQOXOEU5OQZZ2VXXDVZ3PHLQSSC4IHMSWCOZI54EDVYFHHNSW2O3FMY5STYALRA5WMLR25BUTV2DJHLUGOCC==="



# The name to display in the copyright section in the footer
copyrightname = "HOL_LOL"



# The url to use as link in the copyright name in the footer. Leave empty to use none.
copyrighturl = "https://github.com/writer00000000"



# Show the "built on Hugo" disclaimer
showhugo = true



# Urls for social networks



# Enables or disables the loading animations. false activates them. Default is false.
loadfastload = false



# Sets the speed for the page loading effect. Default is 1.0.
loadspeedfactor = 1.0



# Enables or disables the second flyby cursor. Default is false.
loadonepass = true

[params.copyright]
    name = "HOL_LOL"

# The url to use as link in the copyright name in the footer. Leave empty to use none.
url = "https://github.com/writer00000000"



# Text to go before copyright information
prefix = ""



# Text to go between copyright and hugo disclaimer (if enabled)
suffix = ""

[menu]

  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/aboutt/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true